(function(){
'use strict';
const $ = (id) => document.getElementById(id);
const $$ = (sel) => Array.from(document.querySelectorAll(sel));
const state = window.dataStore.getState();
let restSeconds = 60, restTimer = null;

function save(reason){ $('saveDot').className='dot saving'; $('saveText').textContent='Saving...'; window.dataStore.saveState(reason); setTimeout(()=>{$('saveDot').className='dot saved'; $('saveText').textContent='Saved';},180); }
function toast(msg){ const el=$('toast'); el.textContent=msg; el.classList.remove('hidden'); clearTimeout(el._t); el._t=setTimeout(()=>el.classList.add('hidden'),2400); }
function titleCase(v=''){ return String(v).replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase()); }
function subtitle(){ const p=state.profile; return `${titleCase(p.role)} • ${titleCase(p.sport)} • ${window.PIQSportEngine.getPositionLabel(p.sport,p.position)}`; }
function modeText(){ return state.profile.team_mode==='team' ? `Team athlete · ${state.profile.team_code || window.PIQConfig.demoTeamCode}` : 'Solo athlete'; }
function renderShell(){ $('brandSubtitle').textContent = subtitle(); $('viewSubtitle').textContent = subtitle(); $('modeBadge').textContent = modeText(); }
function setView(view){ state.ui.currentView=view; save('view'); $$('.view').forEach(v=>v.classList.add('hidden')); $$('.nav-tab').forEach(b=>b.classList.toggle('active', b.dataset.view===view)); $(view+'View').classList.remove('hidden'); $('viewTitle').textContent=titleCase(view); renderCurrent(); history.replaceState(null,'','#'+view); }
function onboardingRequired(){ return !state.profile.onboarded; }
function metricCards(){ return window.PIQDashboardView.renderCards(state).map(c=>`<div class="card"><div class="muted small">${c.label}</div><div class="metric">${c.value}</div><div class="muted">${c.sub}</div></div>`).join(''); }
function renderDashboard(){ const perf=window.PIQPerformance.summary(state); $('dashboardView').innerHTML=`<div class="grid cards">${metricCards()}</div>
  <div class="row"><div class="panel"><div class="session-header"><h3>Current phase</h3><span class="pill">Week ${currentWeek()}</span></div><p>${window.PIQPeriodization.getPhase(currentWeek()).name}</p><p class="muted">${window.PIQPeriodization.getPhase(currentWeek()).note}</p><div class="list"><div class="list-item"><span>Risk status</span><strong class="${perf.risk.level==='High'?'danger':perf.risk.level==='Medium'?'warning':'good'}">${perf.risk.level}</strong></div><div class="list-item"><span>Recovery note</span><span>${window.PIQAutomation.suggestion(state.profile)}</span></div><div class="list-item"><span>Meal plans</span><span>${state.profile.meal_plan_enabled?'Enabled':'Disabled'}</span></div></div></div>
  <div class="panel"><h3>Weekly load heatmap</h3><div id="heatmap"></div></div></div>
  <div class="panel"><div class="session-header"><h3>Recent sessions</h3><button class="btn ghost" id="generateFromDashboard">Generate next session</button></div>${renderRecentSessions()}</div>`;
  window.PIQHeatmap.render($('heatmap'), state.sessions.slice(-7));
  $('generateFromDashboard').onclick=generateWeek;
 }
 function renderRecentSessions(){ if(!state.sessions.length) return '<p class="muted">No completed sessions yet. Generate a workout to start.</p>'; return `<div class="list">${state.sessions.slice().reverse().slice(0,5).map(s=>`<div class="list-item"><div><strong>${titleCase(s.dayType)}</strong><div class="muted small">${new Date(s.logged_at||s.id.split('_')[1]||Date.now()).toLocaleDateString()}</div></div><div>${s.duration_min} min • RPE ${s.rpe||'—'} • PIQ ${s.piq_score||'—'}</div></div>`).join('')}</div>`; }
 function buildExerciseCard(item, blockIndex, itemIndex){ return `<div class="exercise-card"><div class="exercise-top"><div><strong>${item.name}</strong><div class="muted small">${item.sets} sets • ${item.reps} • Rest ${item.rest_sec}s</div></div><div class="toolbar"><button class="btn ghost swap-btn" data-block="${blockIndex}" data-item="${itemIndex}">Swap</button><button class="btn ghost rest-btn" data-rest="${item.rest_sec}">Rest</button></div></div><div class="exercise-meta"><span class="pill">Coach cue</span><span class="muted">${item.cues}</span></div></div>`; }
 function renderTrain(){ const s=state.currentSession; let html=`<div class="toolbar"><button class="btn primary" id="generateTrainBtn">Generate week</button><button class="btn ghost" id="newSessionBtn">Generate single session</button></div>`; if(!s){ html += `<div class="panel"><h3>No active session</h3><p class="muted">Generate a session from the athlete profile and current phase.</p></div>`; } else { html += `<div class="panel"><div class="session-header"><div><h3>${titleCase(s.dayType)}</h3><div class="muted">${s.phase} phase • ${s.duration_min} min • fatigue ${s.volume_score}</div></div><div class="toolbar"><button class="btn primary" id="completeWorkoutBtn">Complete workout</button></div></div><div class="progress"><span style="width:100%"></span></div><div class="grid">${s.blocks.map((b,bi)=>`<div class="session-block panel"><div class="session-header"><h4>${b.title}</h4><span class="pill">${b.items.length} drills</span></div>${b.items.map((it,ii)=>buildExerciseCard(it,bi,ii)).join('')}</div>`).join('')}</div></div>`; } $('trainView').innerHTML=html; $('generateTrainBtn').onclick=generateWeek; const ns=$('newSessionBtn'); if(ns) ns.onclick=()=>{state.currentSession=window.PIQEliteTraining.generateSession('lower_strength',state.profile,currentWeek()); save('session'); renderTrain(); toast('Single session generated');}; const cw=$('completeWorkoutBtn'); if(cw) cw.onclick=completeWorkout; bindSwapButtons(); bindRestButtons(); }
 function bindSwapButtons(){ $$('.swap-btn').forEach(btn=>btn.onclick=()=>openSwap(Number(btn.dataset.block),Number(btn.dataset.item))); }
 function bindRestButtons(){ $$('.rest-btn').forEach(btn=>btn.onclick=()=>openRest(Number(btn.dataset.rest)||60)); }
 function renderWellness(){ const last=state.wellness.checkins.at(-1); const readiness=window.PIQAnalytics.readiness(state.wellness.checkins); $('wellnessView').innerHTML=`<div class="row"><div class="panel"><h3>Daily readiness</h3><div class="metric">${readiness}</div><p class="muted">Log sleep, energy, soreness, and stress before training.</p><form id="wellnessForm" class="form-grid"><div class="field"><label>Sleep</label><input type="range" min="1" max="10" name="sleep" value="${last?.sleep||7}"></div><div class="field"><label>Energy</label><input type="range" min="1" max="10" name="energy" value="${last?.energy||7}"></div><div class="field"><label>Soreness</label><input type="range" min="1" max="10" name="soreness" value="${last?.soreness||3}"></div><div class="field"><label>Stress</label><input type="range" min="1" max="10" name="stress" value="${last?.stress||4}"></div><div class="field" style="grid-column:1/-1"><button class="btn primary">Save readiness</button></div></form></div><div class="panel"><h3>Risk review</h3><p><strong>${window.PIQRisk.evaluate(state).level}</strong></p><div class="list">${window.PIQRisk.evaluate(state).reasons.map(r=>`<div class="list-item">${r}</div>`).join('') || '<div class="list-item">No active alerts.</div>'}</div></div></div>`; $('wellnessForm').onsubmit=(e)=>{e.preventDefault(); const fd=new FormData(e.target); state.wellness.checkins.push({date:new Date().toISOString(),sleep:+fd.get('sleep'),energy:+fd.get('energy'),soreness:+fd.get('soreness'),stress:+fd.get('stress')}); save('wellness'); renderWellness(); renderDashboard(); toast('Readiness saved');}; }
 function renderTeam(){ if(state.profile.team_mode!=='team' && state.profile.role!=='coach'){ $('teamView').innerHTML='<div class="panel"><h3>Team features are disabled in solo mode</h3><p class="muted">Switch to team mode in settings to unlock announcements, roster, and coach workflows.</p></div>'; return; } const announcements=state.team.announcements.map(a=>`<div class="list-item"><div><strong>${a.title}</strong><div class="muted small">${a.message}</div></div></div>`).join(''); $('teamView').innerHTML=`<div class="grid cards"><div class="card"><div class="muted small">Athletes</div><div class="metric">${state.team.athletes.length}</div></div><div class="card"><div class="muted small">Announcements</div><div class="metric">${state.team.announcements.length}</div></div><div class="card"><div class="muted small">Avg PIQ</div><div class="metric">${Math.round(state.team.athletes.reduce((s,a)=>s+a.piq,0)/state.team.athletes.length)}</div></div><div class="card"><div class="muted small">Avg Readiness</div><div class="metric">${Math.round(state.team.athletes.reduce((s,a)=>s+a.readiness,0)/state.team.athletes.length)}</div></div></div><div class="row"><div class="panel"><h3>Coach announcements</h3><div class="list">${announcements}</div><form id="announcementForm" class="field"><label>New announcement</label><textarea name="message" placeholder="Post a coaching note or team update"></textarea><button class="btn primary" type="submit">Post update</button></form></div><div class="panel"><h3>Workout command</h3><p class="muted">Assign the current week template to the team.</p><button class="btn primary" id="assignTeamBtn">Assign week to team</button></div></div>`; $('announcementForm').onsubmit=(e)=>{e.preventDefault(); const msg=new FormData(e.target).get('message'); if(!msg) return; state.team.announcements.unshift({id:'a'+Date.now(),title:'Coach note',message:String(msg)}); save('announcement'); renderTeam(); toast('Announcement posted');}; $('assignTeamBtn').onclick=()=>toast('Team assignment queued locally'); }
 function renderAthletes(){ const rows=state.team.athletes.map(a=>`<tr><td>${a.name}</td><td>${a.position}</td><td>${a.piq}</td><td>${a.readiness}</td><td>${a.compliance}%</td><td>${a.risk}</td></tr>`).join(''); $('athletesView').innerHTML=`<div class="panel"><h3>Athlete roster</h3><table class="table"><thead><tr><th>Name</th><th>Position</th><th>PIQ</th><th>Readiness</th><th>Compliance</th><th>Risk</th></tr></thead><tbody>${rows}</tbody></table></div>`; }
 function renderAnalytics(){ const piq=window.PIQAnalytics.piq(state), metrics=state.analytics.metrics; $('analyticsView').innerHTML=`<div class="grid cards"><div class="card"><div class="muted small">Strength</div><div class="metric">${piq.strength}</div><div class="muted">Estimated from squat + bench</div></div><div class="card"><div class="muted small">Speed</div><div class="metric">${piq.speed}</div><div class="muted">40-yard sprint normalization</div></div><div class="card"><div class="muted small">Conditioning</div><div class="metric">${piq.conditioning}</div><div class="muted">Load vs control balance</div></div><div class="card"><div class="muted small">Recovery</div><div class="metric">${piq.recovery}</div><div class="muted">Readiness-based recovery score</div></div></div><div class="row"><div class="panel"><h3>Performance metrics</h3><div class="list"><div class="list-item"><span>Vertical jump</span><strong>${metrics.vertical_jump} in</strong></div><div class="list-item"><span>40-yard sprint</span><strong>${metrics.sprint_40}s</strong></div><div class="list-item"><span>Squat estimate</span><strong>${metrics.squat_est} lb</strong></div><div class="list-item"><span>Bench estimate</span><strong>${metrics.bench_est} lb</strong></div></div></div><div class="panel"><h3>PIQ formula</h3><p class="muted">30% strength + 20% speed + 20% conditioning + 15% compliance + 15% recovery.</p><div class="metric">${piq.score}</div></div></div>`; }
 function renderSettings(){ const p=state.profile; const macros=window.PIQNutrition.targets(p); $('settingsView').innerHTML=`<div class="row"><div class="panel">${window.PIQOnboarding.render(state)}</div><div class="panel"><h3>Engine settings</h3><div class="list"><div class="list-item"><span>Meal plan gating</span><strong>${p.meal_plan_enabled?'Enabled':'Disabled'}</strong></div><div class="list-item"><span>Daily protein target</span><strong>${macros.protein} g</strong></div><div class="list-item"><span>Daily carb target</span><strong>${macros.carbs} g</strong></div><div class="list-item"><span>Daily fat target</span><strong>${macros.fats} g</strong></div><div class="list-item"><span>Calories</span><strong>${macros.calories}</strong></div></div></div></div>`; bindOnboarding(); }
 function bindOnboarding(){ const form=$('onboardingForm'); if(!form) return; form.onsubmit=(e)=>{e.preventDefault(); const fd=new FormData(form); Object.assign(state.profile,{name:String(fd.get('name')),role:String(fd.get('role')),sport:String(fd.get('sport')),position:String(fd.get('position')),team_mode:String(fd.get('team_mode')),goal:String(fd.get('goal')),experience:String(fd.get('experience')),training_days:Number(fd.get('training_days')),weight_lbs:Number(fd.get('weight_lbs')),meal_plan_enabled:String(fd.get('meal_plan_enabled'))==='true',equipment:String(fd.get('equipment')).split(',').map(s=>s.trim()).filter(Boolean),team_code:String(fd.get('team_code')),onboarded:true}); save('profile'); renderShell(); renderCurrent(); toast('Profile updated'); } }
 function generateWeek(){ const week=currentWeek(); const sessions=window.PIQEliteTraining.generateWeek(state.profile,week); state.currentSession=sessions[0]; state.generatedWeek=sessions; save('generate_week'); renderTrain(); renderDashboard(); toast('Workout generated'); }
 function currentWeek(){ return ((state.sessions.length)%12)+1; }
 function completeWorkout(){ if(!state.currentSession) return; const rpe=prompt('Session RPE (1-10)?','7'); if(rpe===null) return; window.PIQWorkout.logCompletion(state,state.currentSession,rpe); save('complete'); renderTrain(); renderDashboard(); renderAnalytics(); toast('Workout completed'); }
 function openSwap(blockIndex,itemIndex){ const item=state.currentSession.blocks[blockIndex].items[itemIndex]; const options=window.PIQEliteTraining.swapOptions(item,state.profile); $('swapModalBody').innerHTML = options.length ? `<div class="list">${options.map(o=>`<button class="btn ghost swap-option" data-id="${o.id}">${o.title}</button>`).join('')}</div>` : '<p class="muted">No compatible swaps found with current equipment and difficulty.</p>'; $('swapModal').showModal(); $$('.swap-option').forEach(btn=>{ btn.onclick=()=>{ const ex=window.PIQExerciseLibrary.getById(btn.dataset.id); state.currentSession.blocks[blockIndex].items[itemIndex]={exercise_id:ex.id,name:ex.title,sets:ex.defaultSets,reps:ex.defaultReps,rest_sec:ex.defaultRest,cues:ex.cues.join(' • '),fatigue:ex.fatigue}; state.currentSession.volume_score = state.currentSession.blocks.flatMap(b=>b.items).reduce((s,x)=>s+Number(x.fatigue||0),0); save('swap'); $('swapModal').close(); renderTrain(); toast('Exercise swapped'); }; }); }
 function openRest(sec){ restSeconds=sec; updateRestDisplay(); $('restModal').showModal(); }
 function updateRestDisplay(){ const m=String(Math.floor(restSeconds/60)).padStart(2,'0'); const s=String(restSeconds%60).padStart(2,'0'); $('restDisplay').textContent=`${m}:${s}`; }
 function bindTopbar(){ $('quickGenerateBtn').onclick=generateWeek; $('quickResetBtn').onclick=()=>{ window.dataStore.reset(); location.reload(); }; $('restStartBtn').onclick=()=>{ clearInterval(restTimer); restTimer=setInterval(()=>{restSeconds--; updateRestDisplay(); if(restSeconds<=0){clearInterval(restTimer); toast('Rest complete'); $('restModal').close();}},1000); }; $$('[data-rest]').forEach(btn=>btn.onclick=()=>{ restSeconds=Number(btn.dataset.rest); updateRestDisplay(); }); }
 function renderCurrent(){ if(onboardingRequired()){ $('onboardingGate').classList.remove('hidden'); $('onboardingGate').innerHTML=window.PIQOnboarding.render(state); bindOnboarding(); } else $('onboardingGate').classList.add('hidden'); renderDashboard(); renderTrain(); renderWellness(); renderTeam(); renderAthletes(); renderAnalytics(); renderSettings(); }
 function init(){ renderShell(); bindTopbar(); $$('.nav-tab').forEach(btn=>btn.onclick=()=>setView(btn.dataset.view)); renderCurrent(); const initial=location.hash.replace('#','')||state.ui.currentView||'dashboard'; if($(initial+'View')) setView(initial); if('serviceWorker' in navigator){ navigator.serviceWorker.register('./sw.js').catch(()=>{}); } }
 document.addEventListener('DOMContentLoaded', init);
})();
