window.PIQExerciseLibrary=(function(){
  const exercises=[
    {id:'dead_bug',title:'Dead Bug',type:'core',movement:'anti_extension',equipment:['bodyweight'],difficulty:'beginner',intent:'stability',defaultSets:2,defaultReps:'8/side',defaultRest:30,cues:['Ribs down','Own the exhale'],fatigue:1,joint:1},
    {id:'plank',title:'Plank',type:'core',movement:'anti_extension',equipment:['bodyweight'],difficulty:'beginner',intent:'stability',defaultSets:3,defaultReps:'30s',defaultRest:30,cues:['Straight line','Brace hard'],fatigue:1,joint:1},
    {id:'goblet_squat',title:'Goblet Squat',type:'strength',movement:'squat',equipment:['dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:4,defaultReps:'8-10',defaultRest:75,cues:['Brace before each rep','Sit between hips'],fatigue:3,joint:2},
    {id:'split_squat',title:'Split Squat',type:'strength',movement:'lunge',equipment:['bodyweight','dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:3,defaultReps:'8/side',defaultRest:60,cues:['Vertical torso','Push through front foot'],fatigue:2,joint:2},
    {id:'db_rdl',title:'Dumbbell RDL',type:'strength',movement:'hinge',equipment:['dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:4,defaultReps:'8-10',defaultRest:75,cues:['Hips back','Soft knees'],fatigue:3,joint:2},
    {id:'pushup',title:'Push-Up',type:'strength',movement:'horizontal_push',equipment:['bodyweight'],difficulty:'beginner',intent:'strength',defaultSets:3,defaultReps:'10-15',defaultRest:45,cues:['Body rigid','Chest to floor'],fatigue:2,joint:1},
    {id:'db_bench',title:'Dumbbell Bench Press',type:'strength',movement:'horizontal_push',equipment:['dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:4,defaultReps:'8-10',defaultRest:75,cues:['Control the lower','Drive evenly'],fatigue:3,joint:2},
    {id:'db_row',title:'Dumbbell Row',type:'strength',movement:'horizontal_pull',equipment:['dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:4,defaultReps:'8-10',defaultRest:60,cues:['Row to hip','Stay square'],fatigue:3,joint:2},
    {id:'press',title:'Dumbbell Shoulder Press',type:'strength',movement:'vertical_push',equipment:['dumbbells'],difficulty:'beginner',intent:'strength',defaultSets:3,defaultReps:'8-10',defaultRest:60,cues:['Stack ribs','Press straight up'],fatigue:2,joint:2},
    {id:'pullup',title:'Pull-Up',type:'strength',movement:'vertical_pull',equipment:['bodyweight'],difficulty:'intermediate',intent:'strength',defaultSets:4,defaultReps:'5-8',defaultRest:90,cues:['Drive elbows down','Full hang'],fatigue:3,joint:2},
    {id:'box_jump',title:'Box Jump',type:'power',movement:'plyometric',equipment:['bodyweight'],difficulty:'intermediate',intent:'power',defaultSets:4,defaultReps:'4',defaultRest:75,cues:['Stick the landing','Be explosive'],fatigue:4,joint:3},
    {id:'broad_jump',title:'Broad Jump',type:'power',movement:'plyometric',equipment:['bodyweight'],difficulty:'intermediate',intent:'power',defaultSets:4,defaultReps:'3',defaultRest:75,cues:['Project forward','Land quietly'],fatigue:4,joint:3},
    {id:'accel_sprint',title:'Acceleration Sprint',type:'speed',movement:'sprint',equipment:['bodyweight'],difficulty:'intermediate',intent:'speed',defaultSets:5,defaultReps:'15 yd',defaultRest:90,cues:['Low shin angle','Violent first step'],fatigue:4,joint:3},
    {id:'shuttle_run',title:'Shuttle Run',type:'conditioning',movement:'cod',equipment:['bodyweight'],difficulty:'intermediate',intent:'conditioning',defaultSets:5,defaultReps:'20s',defaultRest:60,cues:['Sink hips','Win first two steps'],fatigue:4,joint:3},
    {id:'tempo_runs',title:'Tempo Runs',type:'conditioning',movement:'conditioning',equipment:['bodyweight'],difficulty:'beginner',intent:'conditioning',defaultSets:6,defaultReps:'60 yd',defaultRest:45,cues:['Smooth pace','Own mechanics'],fatigue:3,joint:2},
    {id:'bike_intervals',title:'Bike Intervals',type:'conditioning',movement:'conditioning',equipment:['machine'],difficulty:'beginner',intent:'conditioning',defaultSets:8,defaultReps:'15/45',defaultRest:0,cues:['Hard start','Controlled recovery'],fatigue:3,joint:1},
    {id:'pallof',title:'Pallof Press',type:'core',movement:'anti_rotation',equipment:['band'],difficulty:'beginner',intent:'stability',defaultSets:3,defaultReps:'10/side',defaultRest:30,cues:['Stay square','Press slowly'],fatigue:1,joint:1}
  ];
  function compatible(ex, equipment){return ex.equipment.some(e=>equipment.includes(e)) || ex.equipment.includes('bodyweight');}
  return {all:()=>exercises.slice(),getById:(id)=>exercises.find(x=>x.id===id),find:(fn)=>exercises.filter(fn),compatible};
})();
